baseurl: /jekyll_hjl
  # 分页
permalink: /:year/:month/:day/:title.html
paginate: 1
paginate_path: "article/:num"

# 转换
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--excerpt-->

gems: ['jekyll-paginate']

exclude: ['open.bat','Gemfile','Gemfile.lock','Guardfile', 'gulpfile.js']

# Collections
collections:
 common:
  output: true
  permalink: /:collection/:title
 ui:
  output: true
  permalink: /:collection/:title
